version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"  
    volumes:
      - ./data:/data/db
  bestprice:

    container_name: bestprice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  mobile_microservice:
    container_name: mobile_microservice
    build:
      context: ./services/mobile_microservice
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mobiles

  laptop_microservice:
    container_name: laptop_microservice
    build:
      context: ./services/laptop_microservice
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/laptops
